### PR TITLE
Feature improve tracing

### PR DESCRIPTION
**Pull request by pointlander**

### CODE REVIEW

**Comment by raji-narayanan** [comment]
@jpark800 : zipkin UI provides filters

**Comment by pointlander** [comment]
Currently, all the tags/annotations will be sent to the tracing server. I could add something like the log levels (or just use the log levels)...

**Comment by jpark800** [comment]
Yes, the log levels sounds fine.

**Comment by raji-narayanan** [comment]
Let's merge as is to master so TIBCO now demo can proceed. And do this change later after TIBCO Now as an add on , unless it's a super easy one to add in

**Pull request merged**
