### PR TITLE
Feature sqld

### PR DESCRIPTION
**Pull request by pointlander**
Adds a service for SQL injection attack detection.

### CODE REVIEW

**Comment by jpark800** [comment]
@pointlander  A large number of files in /vendor folder are pulled in with this PR.

**Comment by pointlander** [comment]
@jpark800 That is for the neural network framework. I could solve this problem by essentially creating my own neural network. I am using a library called Gorgonia which allows users to build expression graphs and then automatically preforms back propagation on the graphs. What I could do is add a feature to Gorgonia which compiles the expression graph into go source code. (This would be a major new feature.) The code could then be imported instead of importing Gorgonia. Only inference would be supported (which is all that is needed).

**Comment by jpark800** [comment]
@pointlander Ok, let's check the license terms.

**Comment by pointlander** [comment]
@jpark800 License info here: https://github.com/gorgonia/gorgonia#dependencies and at the bottom of the README.

**Pull request merged**
